### ISSUE TITLE
query problem

### ISSUE THREAD

**Issue by amitavaghosh1** [synle/sqlui-native#650]
{ "code": "ER_BAD_DB_ERROR", "errno": 1049, "sqlState": "42000", "sqlMessage": "Unknown database ':undefined/users_dev'" }

**Comment by synle** [comment]
Can you provide more details? 
- Which dialect? 
- Which type authentication scheme? 
- Where is the server hosted? Local? Azure? Aws?

**Comment by synle** [comment]
I haven't received any update on this, will close this out for now. When you have the details on the repro steps, feel free to create another ticket.
